.\Manpage pour liboperation.
.\Contact zoeurk.gmail.com
.TH man 3 "16 may 2025" "0.1" "liboperation man page"
.SH NAME
liboperation
.SH SYNOPSIS
operation library documentation
.SH DESCRIPTION
Library for make operations: +,-,*,/(and %), power...
.SH Structures, Macros, Functions
.TP
Environement
.EX
#if __WORDSIZE == 32
	#define BLK 4
	#define C_BLK BLK+1
	#define D_MAX 1000
	#define D_MAX_LIMIT 10000
	#define COEFS { 1, 10, 100, 1000, 10000 }
#else
	#define BLK 9
	#define C_BLK BLK+1
	#define D_MAX 100000000
	#define D_MAX_LIMIT 1000000000
	#define COEFS { 1, 10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000, 1000000000 }
#endif

BLK			== number of bytes in block
D_MAX		== max div in *10
D_MAX_LIMIT	== max size of number
COEFS		== all coeficients for an architecture
.EE
.BR
.TP
#define DOT(res_nbr, bin_ptr)
Remove all numbers == 0 a the end of dot
.BR
.TP
#define ADJUST_0(res_nbr, bin_ptr1, bin_ptr2)
Remove 0 starting the interger number
.BR
.TP
struct bin
.EX
\fBstruct bin\fR{
        \fBunsigned long int\fR num;	/* number itself */
        \fBint\fR nmemb;				/* number of digits */
        \fBint\fR full;				/* if nmemb is max, full = 1 else full = 0 */
        \fBstruct bin\fR *next;		/* next number, NULL if end */
        \fBstruct bin\fR *prev;		/* prev number */
};
.BR
.TP
#define INIT_BIN(num, nmemb, next, prev)
Initialize \fBstruct bin\fR
.BR
.TP
#define ZERO_BIN { 0, 1, 0, NULL, NULL }
Set \fBstruct bin\fR to number \fIzero\fR
.BR
.TP
\fBstruct nbr{
        \fBunsigned long int\fR bval;				/* number of block elements in value */
        \fBunsigned long int\fR bdot;				/* number of block elements in dot */
        \fBint\fR val;							/* number of more elements in value */
        \fBint\fR dot;							/* number of more elements in dot */
        \fBint\fR neg;							/* signe of the number */
        #if  __WORDSIZE != 32
                #define PADDING 0
                #define ZERO(zero_bin) { 0, 0, 1, 0, 0, PADDING, zero_bin, NULL }
                #define INIT_NBR(sig, bval, val, bdot, dot, num, n)
                        { bval, bdot, val, dot, (sig != 0 && sig != '+'), PADDING, num, n }
                int ___;
        #else
                #define ZERO(zero_bin) { 0, 0, 1, 0, 0, zero_bin, NULL }
                #define INIT_NBR(sig, bval, val, bdot, dot, num, n)
                        { bval, bdot, val, dot, (sig != 0 && sig != '+'), num, n }
        #endif
        \fBstruct bin\fR *num;						/* the number */
        \fBchar *n\fR;							/* where is saved the number parsed and converted */
};
.EE
.BR
.TP
#define INIT_NBR(sig, bval, val, bdot, dot, num, n)
Initialize \fBstruct nbr\fR
.BR
.TP
#define ZERO(zero_bin)
Initialize \fBstruct nbr\fR to number \fIzero\fR
.BR
.TP
struct nbr
.EX
\fBstruct nbr\fR{
	\fBchar\fR *n;				/* where is saved the number parsed and converted */
	\fBchar\fR neg;				/* signe of the number */
	\fBstruct bin\fR *num;		/* the number */
	\fBunsigned long int\fR dot;	/* number of elements in dot */
	\fBunsigned long int\fR val;	/* number of elements in value */
};
.EE
.BR
.TP
struct rebcpy
.EX
\fBstruct retbcpy\fR{
        \fBunsigned long int\fR rblk;		/* number of block copyed */
        \fBint\fR rbytes;			/* number of bytes in more copyed */
        #if __WORDSIZE != 32
                #define I_RBCPY { 0, 0, PADDING }
                \fBint\fR ___; 
        #else
                #define I_RBCPY { 0, 0 }
        #endif 
};
\fII_RBCPY\fR initialize \fBstruct retbcpy\fR
.BR
.TP
\fBchar\fR *parse_nbr(\fBchar\fR *n);
Parse number or return NULL
.BR
.TP
\fBstruct nbr\fR *encode_nbr(\fBchar\fR *n);
Convert number which should be parsed by \fBparse_nbr(char *n)\fR to a \fBstruct nbr *\fR.
.BR
.TP
\fBvoid\fR print_nbr(\fBstruct nbr\fR *n);
Print number \fBstruct nbr *\fR
.BR
.TP
\fBvoid\fR *destroy_nbr(\fBstruct nbr\fR *n);
Destroy number \fBstruct nbr *\fR
.BR
.TP
\fBint\fR equal(\fBstruct nbr\fR *num1, \fBstruct nbr\fR *num2);
compare num1 with num2
.PP
return
.EX
0:	if equal
1:	if greater
-1:	if lower
.EE
.BR
.TP
\fBstruct bin\fR *new_num(\fBunsigned long int\fR val, \fBunsigned long int\fR dot);
Alloc a new binary number which can be give to \fI(struct nbr *)->num\fR;
.BR
.TP
\fBvoid\fR *dup_nbr(\fBstruct nbr\fR *num);
duplic number
.BR
.TP
\fBvoid\fR *bymul10(\fBstruct nbr\fR *num, \fBint\fR fac, \fBint\fR faclen);
multiply by fac
.PP
.EX
for 32 bits:
	fac is <= 10000
	faclen is the number of '0' in fac
for 64 bits:
	fac is <= 1000000000
	faclen is the number of '0' in fac
.EE
.BR
.TP
\fBvoid\fR *align_dot(struct nbr *_num, \fBunsigned long int\fR blk, \fBint\fR bytes); /*not used*/
Add blk and bytes of 0 at the end of doted number
.BR
.TP
\fBstruct retbcpy\fR *nbytescpy(\fBstruct bin\fR **b2, \fBstruct bin\fR **b1, \fBint\fR *bstart, \fBunsigned long int\fR lbytes, \fBint\fR bytes);
Copy lbytes of block and bytes from b1 to b2.
.PP
.EX
*bstart:	remember number of bytes for next occurence
lbytes:	number of block of bytes to copy
bytes:	number of bytes to copy
\fI**b2\fR:	must be allocated to the good len;
.EE
.BR
.TP
\fBvoid\fR *addition(\fBstruct nbr\fR *num1, \fBstruct nbr\fR *num2);
addition num1 and num2
.BR
.TP
\fBvoid\fR *soustraction(\fBstruct nbr\fR *num1, \fBstruct nbr\fR *num2);
soustract num2 to num1
.BR
.TP
\fBvoid\fR *multiplication(\fBstruct nbr\fR *num1, \fBstruct nbr\fR *num2);
multiply num1 and num2
.BR
.TP
\fBvoid\fR *ispuissance(\fBstruct nbr\fR *num, \fBint\fR pui);
power of num by pui
.BR
.TP
\fBvoid\fR *spuissance(\fBstruct nbr\fR *num, \fBunsigned long int\fR bpui, \fBint\fR pui);
power of num by bpui (number of block) and pui
.BR
.TP
\fBvoid\fR *division(\fBstruct nbr\fR *num1, \fBstruct nbr\fR *num2, \fBstruct nbr\fR **modulo, \fBunsigned long int\fR scale, \fBint\fR approximation);
divide num1 by num2
.PP
.EX
**modulo:		for the modulo
scale:		scale for divide
approximation:	if an approximation need to be set
.EE
.BR
.TP
\fBvoid\fR *puissance(\fBstruct nbr\fR *num1, \fBstruct nbr\fR *num2, \fBstruct nbr\fR **modulo, \fBunsigned long int\fR scale, \fBint\fR approximation);
power of num1 by num2 (num2 is Integer);
.PP
.EX
modulo:		used if num2 < 0
scale:		used if num2 < 0
approximation:	used if num2 < 0
.EE
.BR
.SH BUGS
.EX
	This man page use english but I'm not sure that is english :/
	NOT FULLY TESTED
	WARNING: NO WARANTY
		(Maybe a lots of bugs)
.EE
.SH AUTHORS
ZoeurK (zoeurk@gmail.com)
