Document: liboperation
Title: Debian liboperation Manual
Author: <insert document author here>
Abstract: This manual describes what liboperation is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/liboperation/liboperation.sgml.gz

Format: postscript
Files: /usr/share/doc/liboperation/liboperation.ps.gz

Format: text
Files: /usr/share/doc/liboperation/liboperation.text.gz

Format: HTML
Index: /usr/share/doc/liboperation/html/index.html
Files: /usr/share/doc/liboperation/html/*.html
